output.forgot_password = {
    fldNameComplet: 'Nome completo',
    fldCPF: 'CPF',
    fldDatebirth: 'Data de nascimento',
    btnContinuar:  'Continuar',
    titleForgotPassword: 'Esqueci minha senha',
    subTitleRecuperarSenha: 'Recuperar senha',
    iconVoltar: '6%,7%',
    fldNewPassword: '50%,43%',
    fldConfirmNewPassword:  'Confirmar nova senha',
    fldConfirCVV: 'Confirmar o CVV do cartão',
    btnTrocarPasswordCard: 'Trocar senha do cartão',
    initialCpf: '370',
    midleCpf:'750',
    newMidleCpf: '948',
    finalCpf: '66',
    txtDatebirthInitial: '07',
    txtDatebirthMidle:'06',
    txtDatebirthFinal: '19',
    txtDatebirthFinal2:'87',
}